[domain]
name = "sameervers3.dev"
project = "domaind"
zone_id = "675db04827f03ee3e341abf7236b9311"

[limits]
max_per_user = 5

[validation]
allowed_record_types = ["A", "AAAA", "CNAME", "TXT", "MX", "URL"]
min_ttl = 60
max_ttl = 86400

[github]
repo_owner = "sameervers3"
repo_name = "domaind"
